# Generated by Django 4.2.7 on 2023-12-28 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_approx'),
    ]

    operations = [
        migrations.AddField(
            model_name='approx',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.city'),
        ),
        migrations.AddField(
            model_name='approx',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.locality'),
        ),
        migrations.AlterField(
            model_name='approx',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.category'),
        ),
    ]
