# Generated by Django 4.2.7 on 2024-01-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='title',
            field=models.CharField(default=2, max_length=500, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='error',
            name='error',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
