# Generated by Django 4.2.7 on 2024-01-11 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_error_title_alter_error_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='socia_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.socialsite'),
        ),
    ]
