# Generated by Django 4.2.7 on 2024-01-11 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_call_status_visit_meeting_follow_up_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='call_status',
            options={},
        ),
        migrations.AlterModelOptions(
            name='follow_up',
            options={},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={},
        ),
    ]
